In [1]:
import pandas as pd

## 1.Introduction to dataFrame

In [7]:
# Create dataFrame: df
df = pd.DataFrame( [   [1,2,3], [4,5,6],[7,8,9],[10,11,12]   ] )
# print(df)
df

    0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

In [8]:
# Create dataFrame: df with columns 
df_column = pd.DataFrame( [  [1,2,3], [4,5,6],[7,8,9],[10,11,12] ], columns=[ "A", "B", "C"]  )
df_column

    A   B   C
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

In [9]:
# Create dataFrame: df with columns and index
df_column_index = pd.DataFrame( [  [1,2,3], [4,5,6],[7,8,9],[10,11,12] ], columns=[ "A", "B", "C"] , index=["year_1", "year_2", "year_3", "year_4"] )
df_column_index

         A   B   C
year_1   1   2   3
year_2   4   5   6
year_3   7   8   9
year_4  10  11  12

## 2. Data loading 

การนำเข้าข้อมูล

In [ ]:
# read_excel() 
import pandas as pd 
df_from_excel = pd.read_excel("./datasets/data_sample.xlsx")
df_from_excel_sheet2 = pd.read_excel("./datasets/data_sample.xlsx", sheet_name="Sheet2" )
df_from_excel_sheet2

In [ ]:
# read_csv() 
df_from_csv = pd.read_csv("./datasets/Salary_Data.csv")
df_from_csv

In [ ]:
# read_csv() from url 
# read_csv(path) 
path = "https://raw.githubusercontent.com/MainakRepositor/Datasets/refs/heads/master/CoffeeAndCodeLT2018%20-%20CoffeeAndCodeLT2018.csv"
df_from_url = pd.read_csv(path)
df_from_url

## 3. Accessing Data with Pandas

การเข้าถึงข้อมูล

In [ ]:
# ตรวจสอบ dataFrame ด้วย .info 
df_from_url.info()

In [ ]:
# เข้าถึงข้อมูลแบบ Columns
# 1. แสดง column 
df_from_url.columns

# ['CodingHours', 'CoffeeCupsPerDay', 'CoffeeTime', 'CodingWithoutCoffee',
#      'CoffeeType', 'CoffeeSolveBugs', 'Gender', 'Country', 'AgeRange']

# 2. เข้าถึง columns   1 columns 
df_from_url["CodingHours"]  # CodingHours
df_from_url['Country']     # Country

# 2. เข้าถึง columns  more than  1 columns 
df_from_url[ ["CodingHours", "Country"] ]
df_from_url[ ['CoffeeType', 'CoffeeSolveBugs', 'Gender', 'CoffeeTime'] ]

In [ ]:
# เข้าถึงข้อมูลแบบ Row  with dataFrame.loc[ row, column ]
# df_from_url.loc[1]
df_from_url.loc[[0,1,2,3,4,5,6,7,8,9]]
df_from_url.loc[0:20]   # row 0 to 20
df_from_url[50:]  # row 50 to 99

In [ ]:
# เข้าถึงข้อมูลแบบ dataFrame.loc[ row, column ]
# ขออนุญาต สร้าง dataFrame ชื่อ coffee 
coffee = df_from_url

# ขอแถวที่ 0 ถึง 20  และ Columns 'CoffeeType' 
coffee.loc[ :20,  'CoffeeType'  ]
# ขอแถวที่ 0 ถึง 20  และ Columns 'CoffeeType' 'Gender'
coffee.loc[ :20,  [ 'CoffeeType', 'Gender']  ]

# ขอ แถวที่ 15 - 50 และ column ที่ 3 - 6
coffee.loc[ 14:49, [ 'CoffeeTime', 'CodingWithoutCoffee', 'CoffeeType', 'CoffeeSolveBugs']]

## 4. Filtering Data

In [ ]:
# 1. Single condition / เงื่อนไขเดียว 
# กรองคนทำงาน CodingHours > 8 
# high_coffee =    coffee["CodingHours"] >8  # Series 
high_coffee =    coffee[ coffee["CodingHours"] >8 ] # dataFrame 

# high_coffee = df[df['salary'] > 50000]

# 2.  Multi condition 
# กรองคนทำงาน CodingHours > 8  และ เป็น เพศหญิง
female_high_coffee =    coffee[ coffee["CodingHours"] >8 and df['Gender'] == 'Female' ] # dataFrame 

# female_high_salary = df[(df['gender'] == 'Female') & (df['salary'] > 30000)]

<class 'pandas.core.frame.DataFrame'>
Index: 23 entries, 4 to 99
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   CodingHours          23 non-null     int64
 1   CoffeeCupsPerDay     23 non-null     int64
 2   CoffeeTime           23 non-null     object
 3   CodingWithoutCoffee  23 non-null     object
 4   CoffeeType           22 non-null     object
 5   CoffeeSolveBugs      23 non-null     object
 6   Gender               23 non-null     object
 7   Country              23 non-null     object
 8   AgeRange             23 non-null     object
dtypes: int64(2), object(7)
memory usage: 1.8+ KB

In [ ]:
'''
titanic 
Step 1 ให้นักศึกษาหาโหลด ข้อมูล titanic จาก Github หรือ โหลดมาเข้าเครื่องตัวเอง 
Step 2 นำเข้าข้อมูลสร้าง DataFrame ชื่อ titanic 
Step 3 สำรวจข้อมูลเบื้องต้นพร้อมสรุป โดยเขียนเป็น Comment # 
Step 4 ให้หาข้อมูลเพื่อตอบคำถามต่อไปนี้ 

. การเข้าถึงข้อมูล (Accessing Data with .loc)
แบบฝึกหัด:
    เข้าถึงข้อมูล คอลัมน์ ‘Name’ ทั้งหมด
    เข้าถึงข้อมูล คอลัมน์ ‘Name’ และ ‘Age’ ของผู้โดยสารทุกคน
    แสดงข้อมูล แถวที่ 10 ของ DataFrame (ใช้ loc)
    แสดงข้อมูล แถวที่ 5–10 ของ DataFrame พร้อมคอลัมน์ ‘Name’ และ ‘Survived’
    เข้าถึงข้อมูลของผู้โดยสารที่ มี PassengerId = 50 (ทุกคอลัมน์)
    เข้าถึงข้อมูลของผู้โดยสาร 5 คนแรก เฉพาะคอลัมน์ ‘Name’, ‘Age’, ‘Sex’
    เข้าถึง ชื่อ (Name) และ ค่าโดยสาร (Fare) ของผู้โดยสารแถวที่ 100–110
    เข้าถึงข้อมูล ผู้โดยสารที่รอดชีวิต (Survived = 1) เฉพาะคอลัมน์ ‘Name’ และ ‘Pclass’
    เข้าถึงข้อมูล ผู้โดยสารที่อยู่ชั้น Pclass = 1 เฉพาะคอลัมน์ ‘Name’, ‘Sex’, ‘Age’
    เข้าถึงข้อมูลแบบกำหนด index + column พร้อมกัน (เช่น แถวที่ 15–20 เฉพาะคอลัมน์ ‘Name’, ‘Age’, ‘Survived’)

3. การกรองข้อมูล (Filtering)
แบบฝึกหัด:
    เลือกเฉพาะข้อมูลผู้โดยสารที่ รอดชีวิต (Survived = 1)
    เลือกเฉพาะข้อมูลผู้โดยสารที่ อายุต่ำกว่า 18 ปี
    เลือกเฉพาะข้อมูลผู้โดยสารที่ เป็นผู้หญิง (Sex = ‘female’) และอยู่ชั้น Pclass = 1
    เลือกเฉพาะผู้โดยสารที่ Fare มากกว่า 100
    เลือกเฉพาะผู้โดยสารที่ อายุไม่เกิน 30 ปี และรอดชีวิต


    '''