In [3]:
import pandas as pd

# ข้อมูล
df = pd.read_csv("./datasets/fruit2.csv")

# df = df.drop(columns ='y')
df

   Size  y   Fruit
0    27  0   lemon
1    35  1  orange
2    39  1  orange
3    21  0   lemon
4    22  0   lemon
5    45  1  orange
6   102  2  pamelo
7   110  2  pamelo
8   120  2  pamelo

In [1]:
# แปลงค่าตัวอักษรให้เป็นตัวเลข 
from sklearn.preprocessing import LabelEncoder

In [4]:
# เรียกใช้งาน 
encoder = LabelEncoder()

# สร้าง column ใหม่ ที่เป็น Label 
df["Label"] = encoder.fit_transform(df["Fruit"])
df

   Size  y   Fruit  Label
0    27  0   lemon      0
1    35  1  orange      1
2    39  1  orange      1
3    21  0   lemon      0
4    22  0   lemon      0
5    45  1  orange      1
6   102  2  pamelo      2
7   110  2  pamelo      2
8   120  2  pamelo      2

In [ ]:
# แปลงกลับ 
# encoder.inverse_transform([0, 1, 2])

In [5]:
class_names = list(df["Fruit"])  # class names or fruit_types
class_names

['lemon',
 'orange',
 'orange',
 'lemon',
 'lemon',
 'orange',
 'pamelo',
 'pamelo',
 'pamelo']

In [6]:
df.columns

Index(['Size', 'y', 'Fruit', 'Label'], dtype='object')

In [ ]:

from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder

X = [[27],                                                              
     [35],                                                              
     [39],                                                              
     [21],                                                              
     [22],                                                                   
     [45],
     [102],
     [110],
     [120],
    ]                                                              

y_names = ['lemon', 'orange', 'orange', 'lemon', 'lemon', 'orange', 'pamelo', 'pamelo', 'Pamelo']

# y = [0, 1, 1, 0, 0, 1, 2, 2, 2]
y_le = LabelEncoder()

y = y_le.fit_transform(y_names)

class_names = list(y_le.classes_)  # class names or fruit_types
print('all class: {}'. format(class_names))

model = DecisionTreeClassifier()
model.fit(X, y)

data = [[125]] # ทดสอบ 
y_predict = model.predict(data)

prd = class_names[y_predict[0]]
print('Result: size {} -> {}'. format(data[0],prd))

In [ ]:
data_feature_names = ['size']
fruit_types = class_names 

import pydotplus
from sklearn.tree import export_graphviz
from IPython.display import Image

dot_data = export_graphviz(model, out_file=None, 
                           feature_names=data_feature_names,  
                           class_names=fruit_types, # 
                           filled=True,
                           rounded=True)


graph = pydotplus.graph_from_dot_data(dot_data)  
Image(graph.create_png())